wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696901536.065626
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.18
      5: 0.15.11
      8:
      - 1
      - 5
      13: darwin-x86_64
